[package]
cairo-version = "2.2.0"
name = "dojo_examples"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
# worl_address should be comented out until 'sozo migrate' is run, you will get the error 'error: Failed to build remote World state.'
# after you succefully run 'sozo migrate' uncomment this line and add your world address
# world_address = "0x223b959926c92e10a5de78a76871fa40cefafbdce789137843df7c7b30e3e0"

# Madara testnet
# rpc_url = "https://api.cartridge.gg/x/shinai/madara"
# account_address = "0x2"
# private_key = "0xc1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d"
